In [4]:
import numpy as np
arr = [6, 7, 8, 9]
print(arr)
print(type(arr))

[6, 7, 8, 9]
<class 'list'>


In [14]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a)
print(a.ndim) # Get the dimension of a with ndim

<class 'numpy.ndarray'>
(4,)
int32
[6 7 8 9]
1


In [22]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)
b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [32]:
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

a = np.array(arr)
print(type(a))

print (a.shape)
print(a.dtype)
print(a.ndim)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)
b.shape

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int32
1
[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [37]:
# a 2x3 array with random values
np.random.random((2, 3))= array( [[0. 60793904, 0. 02881965, 0.73022145 ],[0.34183628, 0.63274067,0. 07945224]])

SyntaxError: invalid syntax (Temp/ipykernel_752/3087283894.py, line 3)